version: '3.3'

services:
  eformprocessingservice:
    image: eformprocessingservice:${buildid}
    build:
      context: .
      dockerfile: eFormProcessingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  loginapiservice:
    image: loginapiservice:${buildid}
    build:
      context: .
      dockerfile: LoginAPIService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
